language: python
sudo: false
python:
  - "2.7"
  - "3.6"

install:
  - pip install poetry

script:
  - poetry install
  - make unit functional

after_success:
  - bash <(curl -s https://codecov.io/bash)


# automated pypi releases
deploy:
  provider: pypi
  user: gabrielfalcao
  password:
    secure: E5KbnpQau7jv/mpHWAs19Y5zBaOHyBXRCGAsTS0S5lEOp/g8EEbjyt5rL7lcIeFAYarIds719BktC5iO+1AQbXOYicS5vDfiVRdLaJ5HPA4v6zyyQzwadFKSqE1Tv11AG9xkFDfBEPLTQmSrpI5cJIY5UoafDnMZe4CbLVETTw8=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
