language: python
sudo: false
python:
  - "2.7"
  - "3.6"

install:
  - pip install pipenv
  - pip install -r development.txt

script:
  - make unit functional

after_success:
  - bash <(curl -s https://codecov.io/bash)
