name: Python 3.7.5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Python Tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Apt
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl

    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v6"
      with:
        default: 3.7.5

    - name: Cache VirtualEnv
      id: cache-venv
      uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-${{ hashFiles('*.txt') }}-python3.7

    - name: Unit Tests
      run: make unit

    - name: Functional Tests
      run: make functional

    - name: Randomize All Tests
      run: make tests

    - name: "Upload coverage results to codecov.io"
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
